//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using _3880_80_FlashStation.PLC;

namespace _3880_80_FlashStation.Configuration {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "11.0.0.0")]
    internal sealed partial class PlcConfigurationFileTest : global::System.Configuration.ApplicationSettingsBase {
        
        private static PlcConfigurationFileTest defaultInstance = ((PlcConfigurationFileTest)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new PlcConfigurationFileTest())));
        
        public static PlcConfigurationFileTest Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public PlcCommunicatorBase.PlcConfig[] Configuration {
            get {
                return ((PlcCommunicatorBase.PlcConfig[])(this["Configuration"]));
            }
            set {
                this["Configuration"] = value;
            }
        }
    }
}
