//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _3880_80_FlashStation.Configuration {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "11.0.0.0")]
    internal sealed partial class PlcConfiguration : global::System.Configuration.ApplicationSettingsBase {
        
        private static PlcConfiguration defaultInstance = ((PlcConfiguration)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new PlcConfiguration())));
        
        public static PlcConfiguration Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("192.168.10.1")]
        public string PlcIpAddress {
            get {
                return ((string)(this["PlcIpAddress"]));
            }
            set {
                this["PlcIpAddress"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("102")]
        public int PlcPortNumber {
            get {
                return ((int)(this["PlcPortNumber"]));
            }
            set {
                this["PlcPortNumber"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int PlcRackNumber {
            get {
                return ((int)(this["PlcRackNumber"]));
            }
            set {
                this["PlcRackNumber"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int PlcSlotNumber {
            get {
                return ((int)(this["PlcSlotNumber"]));
            }
            set {
                this["PlcSlotNumber"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int PlcReadDbNumber {
            get {
                return ((int)(this["PlcReadDbNumber"]));
            }
            set {
                this["PlcReadDbNumber"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int PlcReadStartAddress {
            get {
                return ((int)(this["PlcReadStartAddress"]));
            }
            set {
                this["PlcReadStartAddress"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int PlcReadLength {
            get {
                return ((int)(this["PlcReadLength"]));
            }
            set {
                this["PlcReadLength"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int PlcWriteDbNumber {
            get {
                return ((int)(this["PlcWriteDbNumber"]));
            }
            set {
                this["PlcWriteDbNumber"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int PlcWriteStartAddress {
            get {
                return ((int)(this["PlcWriteStartAddress"]));
            }
            set {
                this["PlcWriteStartAddress"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int PlcWriteLength {
            get {
                return ((int)(this["PlcWriteLength"]));
            }
            set {
                this["PlcWriteLength"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-1")]
        public int ConfigurationStatus {
            get {
                return ((int)(this["ConfigurationStatus"]));
            }
            set {
                this["ConfigurationStatus"] = value;
            }
        }
    }
}
