//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Linq.Expressions;
using System.Windows.Media.Imaging;
using _3880_80_FlashStation.PLC;

namespace _3880_80_FlashStation.Configuration {

    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "11.0.0.0")]
    internal sealed partial class PlcConfigurationFile : global::System.Configuration.ApplicationSettingsBase {
        
        private static PlcConfigurationFile defaultInstance = ((PlcConfigurationFile)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new PlcConfigurationFile())));

        private static PlcConfigurationFile[] configurations = createConfigurationFileArray(8);
        
        public static PlcConfigurationFile Default { get { return defaultInstance; }}
        public static PlcConfigurationFile[] Configurations { get { return configurations; }}
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public PlcCommunicatorBase.PlcConfig Configuration
        {
            get {
                return ((PlcCommunicatorBase.PlcConfig)(this["Configuration"]));
            }
            set {
                this["Configuration"] = value;
            }
        }

        private static PlcConfigurationFile[] createConfigurationFileArray(int size)
        {
            var array = new PlcConfigurationFile[size + 1];
            array[0] = null;

            for (int i = 0; i < size; i++)
            {
                array[i + 1] = ((PlcConfigurationFile)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new PlcConfigurationFile())));
            }
            return array;
        }
    }
}
