//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;

namespace _3880_80_FlashStation.PLC {
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "11.0.0.0")]
    public sealed partial class PlcConfigurationFile : global::System.Configuration.ApplicationSettingsBase {
        
        private static PlcConfigurationFile defaultInstance = ((PlcConfigurationFile)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new PlcConfigurationFile())));
        
        public static PlcConfigurationFile Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
                                                                     <ArrayOfPlcConfig xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
                                                                        <PlcConfig>
                                                                            <PlcPortNumber>0</PlcPortNumber>
                                                                            <PlcRackNumber>0</PlcRackNumber>
                                                                            <PlcSlotNumber>0</PlcSlotNumber>
                                                                            <PlcReadDbNumber>0</PlcReadDbNumber>
                                                                            <PlcReadStartAddress>0</PlcReadStartAddress>
                                                                            <PlcReadLength>0</PlcReadLength>
                                                                            <PlcWriteDbNumber>0</PlcWriteDbNumber>
                                                                            <PlcWriteStartAddress>0</PlcWriteStartAddress>
                                                                            <PlcWriteLength>0</PlcWriteLength>
                                                                            <PlcConfigurationStatus>0</PlcConfigurationStatus>
                                                                        </PlcConfig>
                                                                        <PlcConfig>
                                                                            <PlcPortNumber>0</PlcPortNumber>
                                                                            <PlcRackNumber>0</PlcRackNumber>
                                                                            <PlcSlotNumber>0</PlcSlotNumber>
                                                                            <PlcReadDbNumber>0</PlcReadDbNumber>
                                                                            <PlcReadStartAddress>0</PlcReadStartAddress>
                                                                            <PlcReadLength>0</PlcReadLength>
                                                                            <PlcWriteDbNumber>0</PlcWriteDbNumber>
                                                                            <PlcWriteStartAddress>0</PlcWriteStartAddress>
                                                                            <PlcWriteLength>0</PlcWriteLength>
                                                                            <PlcConfigurationStatus>0</PlcConfigurationStatus>
                                                                        </PlcConfig>
                                                                        <PlcConfig>
                                                                            <PlcPortNumber>0</PlcPortNumber>
                                                                            <PlcRackNumber>0</PlcRackNumber>
                                                                            <PlcSlotNumber>0</PlcSlotNumber>
                                                                            <PlcReadDbNumber>0</PlcReadDbNumber>
                                                                            <PlcReadStartAddress>0</PlcReadStartAddress>
                                                                            <PlcReadLength>0</PlcReadLength>
                                                                            <PlcWriteDbNumber>0</PlcWriteDbNumber>
                                                                            <PlcWriteStartAddress>0</PlcWriteStartAddress>
                                                                            <PlcWriteLength>0</PlcWriteLength>
                                                                            <PlcConfigurationStatus>0</PlcConfigurationStatus>
                                                                        </PlcConfig>
                                                                        <PlcConfig>
                                                                            <PlcPortNumber>0</PlcPortNumber>
                                                                            <PlcRackNumber>0</PlcRackNumber>
                                                                            <PlcSlotNumber>0</PlcSlotNumber>
                                                                            <PlcReadDbNumber>0</PlcReadDbNumber>
                                                                            <PlcReadStartAddress>0</PlcReadStartAddress>
                                                                            <PlcReadLength>0</PlcReadLength>
                                                                            <PlcWriteDbNumber>0</PlcWriteDbNumber>
                                                                            <PlcWriteStartAddress>0</PlcWriteStartAddress>
                                                                            <PlcWriteLength>0</PlcWriteLength>
                                                                            <PlcConfigurationStatus>0</PlcConfigurationStatus>
                                                                        </PlcConfig>
                                                                        <PlcConfig>
                                                                            <PlcPortNumber>0</PlcPortNumber>
                                                                            <PlcRackNumber>0</PlcRackNumber>
                                                                            <PlcSlotNumber>0</PlcSlotNumber>
                                                                            <PlcReadDbNumber>0</PlcReadDbNumber>
                                                                            <PlcReadStartAddress>0</PlcReadStartAddress>
                                                                            <PlcReadLength>0</PlcReadLength>
                                                                            <PlcWriteDbNumber>0</PlcWriteDbNumber>
                                                                            <PlcWriteStartAddress>0</PlcWriteStartAddress>
                                                                            <PlcWriteLength>0</PlcWriteLength>
                                                                            <PlcConfigurationStatus>0</PlcConfigurationStatus>
                                                                        </PlcConfig>
                                                                        <PlcConfig>
                                                                            <PlcPortNumber>0</PlcPortNumber>
                                                                            <PlcRackNumber>0</PlcRackNumber>
                                                                            <PlcSlotNumber>0</PlcSlotNumber>
                                                                            <PlcReadDbNumber>0</PlcReadDbNumber>
                                                                            <PlcReadStartAddress>0</PlcReadStartAddress>
                                                                            <PlcReadLength>0</PlcReadLength>
                                                                            <PlcWriteDbNumber>0</PlcWriteDbNumber>
                                                                            <PlcWriteStartAddress>0</PlcWriteStartAddress>
                                                                            <PlcWriteLength>0</PlcWriteLength>
                                                                            <PlcConfigurationStatus>0</PlcConfigurationStatus>
                                                                        </PlcConfig>
                                                                        <PlcConfig>
                                                                            <PlcPortNumber>0</PlcPortNumber>
                                                                            <PlcRackNumber>0</PlcRackNumber>
                                                                            <PlcSlotNumber>0</PlcSlotNumber>
                                                                            <PlcReadDbNumber>0</PlcReadDbNumber>
                                                                            <PlcReadStartAddress>0</PlcReadStartAddress>
                                                                            <PlcReadLength>0</PlcReadLength>
                                                                            <PlcWriteDbNumber>0</PlcWriteDbNumber>
                                                                            <PlcWriteStartAddress>0</PlcWriteStartAddress>
                                                                            <PlcWriteLength>0</PlcWriteLength>
                                                                            <PlcConfigurationStatus>0</PlcConfigurationStatus>
                                                                        </PlcConfig>
                                                                        <PlcConfig>
                                                                            <PlcPortNumber>0</PlcPortNumber>
                                                                            <PlcRackNumber>0</PlcRackNumber>
                                                                            <PlcSlotNumber>0</PlcSlotNumber>
                                                                            <PlcReadDbNumber>0</PlcReadDbNumber>
                                                                            <PlcReadStartAddress>0</PlcReadStartAddress>
                                                                            <PlcReadLength>0</PlcReadLength>
                                                                            <PlcWriteDbNumber>0</PlcWriteDbNumber>
                                                                            <PlcWriteStartAddress>0</PlcWriteStartAddress>
                                                                            <PlcWriteLength>0</PlcWriteLength>
                                                                            <PlcConfigurationStatus>0</PlcConfigurationStatus>
                                                                        </PlcConfig>
                                                                        <PlcConfig>
                                                                            <PlcPortNumber>0</PlcPortNumber>
                                                                            <PlcRackNumber>0</PlcRackNumber>
                                                                            <PlcSlotNumber>0</PlcSlotNumber>
                                                                            <PlcReadDbNumber>0</PlcReadDbNumber>
                                                                            <PlcReadStartAddress>0</PlcReadStartAddress>
                                                                            <PlcReadLength>0</PlcReadLength>
                                                                            <PlcWriteDbNumber>0</PlcWriteDbNumber>
                                                                            <PlcWriteStartAddress>0</PlcWriteStartAddress>
                                                                            <PlcWriteLength>0</PlcWriteLength>
                                                                            <PlcConfigurationStatus>0</PlcConfigurationStatus>
                                                                        </PlcConfig>
                                                                    </ArrayOfPlcConfig>")]
        public PlcCommunicatorBase.PlcConfig[] Configuration {
            get {
                return ((PlcCommunicatorBase.PlcConfig[])(this["Configuration"]));
            }
            set {
                this["Configuration"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
                                                                     <ArrayOfBoolean xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance""
                                                                        xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
                                                                        <boolean>false</boolean>
                                                                        <boolean>false</boolean>
                                                                        <boolean>false</boolean>
                                                                        <boolean>false</boolean>
                                                                        <boolean>false</boolean>
                                                                        <boolean>false</boolean>
                                                                        <boolean>false</boolean>
                                                                        <boolean>false</boolean>
                                                                        <boolean>false</boolean>
                                                                    </ArrayOfBoolean>")]
        public Boolean[] ConnectAtStartUp
        {
            get
            {
                return ((Boolean[])(this["ConnectAtStartUp"]));
            }
            set
            {
                this["ConnectAtStartUp"] = value;
            }
        }
    }
}
