//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _PlcAgent.DB {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "11.0.0.0")]
    public sealed partial class DbConnectionHandlerFile : global::System.Configuration.ApplicationSettingsBase {
        
        private static DbConnectionHandlerFile defaultInstance = ((DbConnectionHandlerFile)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new DbConnectionHandlerFile())));
        
        public static DbConnectionHandlerFile Default {
            get {
                return defaultInstance;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<ArrayOfString>
                                                                        <string>WIN-IGCFP7C5SC0\\SQLEXPRESS</string>
                                                                        <string>WIN-IGCFP7C5SC0\\SQLEXPRESS</string>
                                                                        <string>WIN-IGCFP7C5SC0\\SQLEXPRESS</string>
                                                                        <string>WIN-IGCFP7C5SC0\\SQLEXPRESS</string>
                                                                        <string>WIN-IGCFP7C5SC0\\SQLEXPRESS</string>
                                                                        <string>WIN-IGCFP7C5SC0\\SQLEXPRESS</string>
                                                                        <string>WIN-IGCFP7C5SC0\\SQLEXPRESS</string>
                                                                        <string>WIN-IGCFP7C5SC0\\SQLEXPRESS</string>
                                                                        <string>WIN-IGCFP7C5SC0\\SQLEXPRESS</string>
                                                                    </ArrayOfString>")]
        public string[] DbInstances
        {
            get { return ((string[])(this["DbInstances"])); }
            set { this["DbInstances"] = value; }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<ArrayOfString>
                                                                        <string>PlcAgent</string>
                                                                        <string>PlcAgent</string>
                                                                        <string>PlcAgent</string>
                                                                        <string>PlcAgent</string>
                                                                        <string>PlcAgent</string>
                                                                        <string>PlcAgent</string>
                                                                        <string>PlcAgent</string>
                                                                        <string>PlcAgent</string>
                                                                        <string>PlcAgent</string>
                                                                    </ArrayOfString>")]
        public string[] InitialCatalogs
        {
            get { return ((string[])(this["InitialCatalogs"])); }
            set { this["InitialCatalogs"] = value; }
        }
    }
}
