//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;

namespace _3880_80_FlashStation.MainRegistry {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "11.0.0.0")]
    internal sealed partial class MainRegistryFile : global::System.Configuration.ApplicationSettingsBase {
        
        private static MainRegistryFile defaultInstance = ((MainRegistryFile)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new MainRegistryFile())));
        
        public static MainRegistryFile Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public uint[][] PlcCommunicators {
            get {
                return ((uint[][])(this["PlcCommunicators"]));
            }
            set {
                this["PlcCommunicators"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public uint[][] CommunicationInterfaceHandlers {
            get {
                return ((uint[][])(this["CommunicationInterfaceHandlers"]));
            }
            set {
                this["CommunicationInterfaceHandlers"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public uint[][] OutputWriters {
            get {
                return ((uint[][])(this["OutputWriters"]));
            }
            set {
                this["OutputWriters"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public uint[][] VFlashTypeBanks {
            get {
                return ((uint[][])(this["VFlashTypeBanks"]));
            }
            set {
                this["VFlashTypeBanks"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public uint[][] VFlashHandlers {
            get {
                return ((uint[][])(this["VFlashHandlers"]));
            }
            set {
                this["VFlashHandlers"] = value;
            }
        }
    }
}
