//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _PlcAgent.Analyzer {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "11.0.0.0")]
    public sealed partial class AnalyzerSetupFile : global::System.Configuration.ApplicationSettingsBase {
        
        private static AnalyzerSetupFile defaultInstance = ((AnalyzerSetupFile)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new AnalyzerSetupFile())));
        
        public static AnalyzerSetupFile Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<ArrayOfInt>
                                                                        <int>0</int>
                                                                        <int>0</int>
                                                                        <int>0</int>
                                                                        <int>0</int>
                                                                        <int>0</int>
                                                                        <int>0</int>
                                                                        <int>0</int>
                                                                        <int>0</int>
                                                                        <int>0</int>
                                                                    </ArrayOfInt>")]
        public int[] SampleTime {
            get {
                return ((int[])(this["SampleTime"]));
            }
            set {
                this["SampleTime"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<ArrayOfDouble>
                                                                        <double>0.0</double>
                                                                        <double>0.0</double>
                                                                        <double>0.0</double>
                                                                        <double>0.0</double>
                                                                        <double>0.0</double>
                                                                        <double>0.0</double>
                                                                        <double>0.0</double>
                                                                        <double>0.0</double>
                                                                        <double>0.0</double>
                                                                    </ArrayOfDouble>")]
        public double[] TimeRange {
            get {
                return ((double[])(this["TimeRange"]));
            }
            set {
                this["TimeRange"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int NumberOfChannels {
            get {
                return ((int)(this["NumberOfChannels"]));
            }
            set {
                this["NumberOfChannels"] = value;
            }
        }
    }
}
