//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _3880_80_FlashStation.Output {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "11.0.0.0")]
    internal sealed partial class OutputCreatorFile : global::System.Configuration.ApplicationSettingsBase {
        
        private static OutputCreatorFile defaultInstance = ((OutputCreatorFile)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new OutputCreatorFile())));
        
        public static OutputCreatorFile Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int[] StartAddress {
            get {
                return ((int[])(this["StartAddress"]));
            }
            set {
                this["StartAddress"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int[] EndAddress {
            get {
                return ((int[])(this["EndAddress"]));
            }
            set {
                this["EndAddress"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int[] SelectedIndex {
            get {
                return ((int[])(this["SelectedIndex"]));
            }
            set {
                this["SelectedIndex"] = value;
            }
        }
    }
}
