//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ttAgent.Vector {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "11.0.0.0")]
    internal sealed partial class VFlashTypeBankFile : global::System.Configuration.ApplicationSettingsBase {
        
        private static VFlashTypeBankFile defaultInstance = ((VFlashTypeBankFile)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new VFlashTypeBankFile())));
        
        public static VFlashTypeBankFile Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<ArrayOfArrayOfString>
                                                                            <ArrayOfString />
                                                                            <ArrayOfString />
                                                                            <ArrayOfString />
                                                                            <ArrayOfString />
                                                                            <ArrayOfString />
                                                                            <ArrayOfString />
                                                                            <ArrayOfString />
                                                                            <ArrayOfString />
                                                                            <ArrayOfString />
                                                                        </ArrayOfArrayOfString>")]
        public string[][] TypeBank {
            get {
                return ((string[][])(this["TypeBank"]));
            }
            set {
                this["TypeBank"] = value;
            }
        }
    }
}
